steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cicd-demo-458507/cicd/flask-cicd-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cicd-demo-458507/cicd/flask-cicd-app:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'flask-cicd-app',
        '--image', 'us-central1-docker.pkg.dev/cicd-demo-458507/cicd/flask-cicd-app:$SHORT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'us-central1-docker.pkg.dev/cicd-demo-458507/cicd/flask-cicd-app:$SHORT_SHA'
